-- Durable issue-run dispatch queue for RaT Ops Admin.
-- Allows recommendation approvals and issue automation to create durable worker runs
-- that a local OpenClaw dispatcher can claim and execute.

create table if not exists public.admin_issue_runs (
  id bigint generated by default as identity primary key,
  issue_id text not null references public.admin_issues(id) on delete cascade,
  issue_number integer not null,
  project text not null,
  owner_agent text not null default 'execution',
  run_id text,
  cwd text,
  claimed_by text,
  task_title text not null,
  source text not null default 'recommendation-approval',
  status text not null default 'queued',
  priority text not null default 'normal',
  dispatch_payload jsonb not null default '{}'::jsonb,
  raw_spawn_result text,
  result_summary text,
  failure_category text,
  failure_message text,
  started_at timestamptz,
  claimed_at timestamptz,
  completed_at timestamptz,
  duration_ms integer,
  estimated_cost_usd numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_issue_runs_status_check check (status in ('queued', 'running', 'completed', 'failed', 'canceled', 'retrying'))
);

alter table public.admin_issue_runs add column if not exists cwd text;
alter table public.admin_issue_runs add column if not exists claimed_by text;
alter table public.admin_issue_runs add column if not exists priority text not null default 'normal';
alter table public.admin_issue_runs add column if not exists dispatch_payload jsonb not null default '{}'::jsonb;
alter table public.admin_issue_runs add column if not exists raw_spawn_result text;
alter table public.admin_issue_runs add column if not exists result_summary text;
alter table public.admin_issue_runs add column if not exists failure_category text;
alter table public.admin_issue_runs add column if not exists failure_message text;
alter table public.admin_issue_runs add column if not exists claimed_at timestamptz;
alter table public.admin_issue_runs add column if not exists completed_at timestamptz;
alter table public.admin_issue_runs add column if not exists duration_ms integer;
alter table public.admin_issue_runs add column if not exists estimated_cost_usd numeric;

create index if not exists admin_issue_runs_status_created_idx
  on public.admin_issue_runs(status, created_at asc);

create index if not exists admin_issue_runs_issue_idx
  on public.admin_issue_runs(issue_id, created_at desc);

create index if not exists admin_issue_runs_started_idx
  on public.admin_issue_runs(started_at desc);

create unique index if not exists admin_issue_runs_one_active_issue_idx
  on public.admin_issue_runs(issue_id)
  where status in ('queued', 'running', 'retrying');
