-- Durable recommendation approval queue for /admin/recommendations.
-- Run in Supabase SQL editor for the RaT Studios admin project.

create table if not exists public.admin_recommendations (
  id text primary key,
  slug text not null unique,
  title text not null,
  app_product text not null,
  category text not null default 'other',
  severity text not null default 'medium',
  priority text not null default 'P3',
  effort text not null default 'medium',
  impact text not null default 'medium',
  rationale text not null default '',
  risk_if_ignored text not null default '',
  evidence_links jsonb not null default '[]'::jsonb,
  status text not null default 'recommended',
  approval_notes text,
  implementation_notes text,
  decision_by text,
  decision_at timestamptz,
  decision_notes text,
  converted_issue_id text,
  action_history jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_recommendations_status_check check (status in ('recommended', 'approved', 'rejected', 'deferred', 'implemented')),
  constraint admin_recommendations_priority_check check (priority in ('P1', 'P2', 'P3', 'P4'))
);

create index if not exists admin_recommendations_status_idx on public.admin_recommendations(status);
create index if not exists admin_recommendations_updated_at_idx on public.admin_recommendations(updated_at desc);
create index if not exists admin_recommendations_app_product_idx on public.admin_recommendations(app_product);

create table if not exists public.admin_recommendation_decisions (
  id bigint generated by default as identity primary key,
  recommendation_id text not null references public.admin_recommendations(id) on delete cascade,
  action text not null,
  status text not null,
  decided_by text,
  notes text,
  converted_issue_id text,
  created_at timestamptz not null default now()
);

create index if not exists admin_recommendation_decisions_recommendation_id_idx
  on public.admin_recommendation_decisions(recommendation_id, created_at desc);

create table if not exists public.admin_schedules (
  id uuid primary key,
  owner_user_id uuid,
  project text not null,
  agent_name text not null,
  task_title text not null,
  cron_expression text not null,
  timezone text not null default 'America/Denver',
  environment text not null default 'prod',
  enabled boolean not null default true,
  owner_label text,
  task_payload jsonb not null default '{}'::jsonb,
  last_run_at timestamptz,
  next_run_at timestamptz,
  last_status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_schedules_last_status_check check (last_status in ('pending', 'completed', 'failed'))
);

create index if not exists admin_schedules_enabled_idx on public.admin_schedules(enabled);
create index if not exists admin_schedules_next_run_at_idx on public.admin_schedules(next_run_at);
create index if not exists admin_schedules_updated_at_idx on public.admin_schedules(updated_at desc);

-- Optional seed example. Insert existing data/recommendations-store.json rows through the app/admin flow
-- or a one-time script; runtime display still falls back to local JSON for rows not yet in Supabase.
